import { Router } from "express";
import { analyzeMoodPrompt } from "../services/ai.service";
import axios from "axios";

const router = Router();

router.post("/generate", async (req, res) => {
  try {
    const { prompt } = req.body;
    if (!prompt?.trim()) {
      return res.status(400).json({
        error: "Prompt required",
      });
    }
    if (prompt.trim().length < 3) {
      return res.status(400).json({
        error: "Please describe your music vibe properly",
      });
    }
    const analysis = await analyzeMoodPrompt(prompt);
    const accessToken = req.headers.authorization?.split(" ")[1];
    console.log("Step 1: Searching tracks...");

    const spotifyResponse1 = await axios.get(
      `https://api.spotify.com/v1/search`,

      {
        params: {
          q: analysis.searchQuery,

          type: "track",

          limit: 10,

          offset: 0,

          market: "IN",
        },

        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      },
    );

    const spotifyResponse2 = await axios.get(
      `https://api.spotify.com/v1/search`,

      {
        params: {
          q: analysis.searchQuery,

          type: "track",

          limit: 10,

          offset: 10,

          market: "IN",
        },

        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      },
    );

    const allTracks = [
      ...spotifyResponse1.data.tracks.items,

      ...spotifyResponse2.data.tracks.items,
    ];

    console.log("Step 2: Fetching user...");

    const userResponse = await axios.get("https://api.spotify.com/v1/me", {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });

    console.log("Step 3: Creating playlist...");

    const playlistResponse = await axios.post(
      `https://api.spotify.com/v1/me/playlists`,
      {
        name: analysis.playlistTitle,
        description: "Generated by Moodify",
        public: true,
      },
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
      },
    );

    const playlistId = playlistResponse.data.id;

    const trackUris = allTracks

      .filter((track: any) => track && track.uri)

      .map((track: any) => track.uri);

    console.log("Step 4: Adding tracks...");

    const addResponse = await axios.post(
      `https://api.spotify.com/v1/playlists/${playlistId}/items`,

      {
        uris: trackUris,
      },

      {
        headers: {
          Authorization: `Bearer ${accessToken}`,

          "Content-Type": "application/json",
        },
      },
    );

    console.log("ADD RESPONSE:", addResponse.data);

    res.json({
      playlist: playlistResponse.data,

      added: addResponse.data,
    });
  } catch (error: any) {
    res.status(500).json({
      error: error.message,
    });
  }
});

export default router;
